baseurl = "https://about.zyradyl.moe"
contentdir    = "content"
layoutdir     = "layouts"
publishdir    = "public"
title = "About"
canonifyurls  = true

DefaultContentLanguage = "en"
theme = "stip"
metaDataFormat = "yaml"
pygmentsUseClasses = true
pygmentCodeFences = true
#disqusShortname = "XXX"
#googleAnalytics = "XXX"

[Author]
    name = "Zyradyl"
    bio = "Calm Healer/Angry Technomage"

[params.colors]
  background = "#000000"
  circle = "#333399"
  foreground = "#d98cd9"
  hover = "#993399"

[params]
    [[params.links]]
        iconset = "fas"
        icon = "home"
        title = "Home"
        url = "https://zyradyl.moe"
    [[params.links]]
        iconset = "fas"
        icon = "archive"
        title = "Archive"
        url = "https://archive.zyradyl.moe/about"
    [[params.links]]
        iconset = "fab"
        icon = "discord"
        title = "Discord"
        url = "https://discord.gg/mA8PMGV"
